### PR TITLE
Debug, optimize, modernize and add some functions to the package.

### PR DESCRIPTION
**Pull request by niruvt**
Hello,

First of all thanks a lot for working on this important issue. I appreciate your idea and work. As the title suggests, I have done 4 things to your package and this is a pull request in the hope that you would find it worthy.

## Debugging

Unfortunately your package wasn't compiling at all. It had a stray `\csname\endcsname` in the sty file. I have removed it. Your documentation had a lot of overfull boxes because of the use of `\\` in the documentation. I have removed all those boxes and made it look slightly better. Example use-cases in your documentation were producing wrong results with your package, e.g., `The tone system of \liso{ptk} is fascinating.` doesn't produce what your documentation says. I had a really hard time with this 😂. It turned out that there is no code `ptk` available in any of the files. Hence I have changed the example a bit with a consistent one. (A tip: Don't ever write things manually when demonstrating the use of a macro, it can produce misleading results. Directly use the macro, so that you also get to know whether your thing is working correctly or not.)

## Optimizing

1. `xkeyval` is a very slow package. `expkv-opt` and `expkv-def` are new packages which provide similar functionality with better speed and reliability. You can refer to the documentation of `expkv` for a detailed comparison of performance of key-val packages. Considering these facts I have replaced `xkeyval` with `expkv`.
2. You don't need key-value at all. All of what you want can be achieved with simple macros. Macros are better for speed than keys and speed up the compilation. I have completely rebuilt the mechanism and added notes regarding it in the documentation.

## Modernizing

You were using `ltxdoc` class which didn't successfully produce any pdf because of hyperref clash. A better class named `l3doc` is available which I have used. Now your document compiles without pain. These days `\NeedsTexFormat` line has become unnecessary. I have omitted it.

## Additions

I have added three macros for changing the mode locally, i.e., changing to `wals` when you have loaded the package with `glottolog`. The macros are pretty peasy: `\changetoglottolog`, `\changetowals`, `\changetonone` (sounds contradictory, but I have adhered to your naming and this macro changes the style to `none` 😛).

### CODE REVIEW

**Comment by niruvt** [comment]
I have almost zero experience with Python, so if you like these changes, kindly make sure to match the Python code to output the current files.

**Comment by niruvt** [comment]
The speed of my package is around six and a half times faster than that of yours. I tested this with the latest benchmarking tool developed by the LaTeX team, namely `l3benchmark`. You can download [these files](https://github.com/cicervlvs/langnames/files/9493680/testing.zip) and test it yourself. On my GNU/Linux machine with fully updated TeX Live 2022, this test returned the following (can be seen in `langnames-test.log`).

```
\keytest / \cmdtest 
6.546
6.546
6.546
```

This means that the first one from the list of two macros given as `\firstmacro / \secondmacro` is six and a half times slower. If you see the tex code, it simply is your approach and the latter is mine.

**Comment by niruvt** [comment]
Oh and to quote Paulo Cereda :joy:,

> Benchmarks are like air conditioners. They don't work as soon as you open Windows.

**Comment by niruvt** [comment]
I forgot mentioning a very important person, Jonathan Spratte. He has generously helped me for testing with the `l3benchmark` tool. The concerned discussion can be found [here](https://topanswers.xyz/tex?q=2096#a2348).

**Comment by cicervlvs** [comment]
Hello,

Thank you so much for all your work! I am surprised (and disappointed in myself) that the package didn't compile for you, as when I tested it it seemed to work without problems. Same with the PDF generation, and actually also with the `\liso{ptk}` example (which you're completely right, I should use the actual command in the documentation). But I  completely trust that the things you've changed in that regard are better and will work more reliably, as you seem to have more experience writing LaTeX packages than I do, and I seem to have been following documentation and tutorials which were a bit outdated.

As for the key-value aspect, I also trust you with that. The solution with `xkeyval` was something I came up with after scratching my head for a while, and I'm glad to learn that there is a better, faster way to do things.

I will review and test the code to ensure that everything works on my end and most likely approve this and make the appropriate changes to the Python script. Thank you again for all the work!

**Comment by niruvt** [comment]
Yayy! I am glad that you liked these ideas.

> I tested it it seemed to work without problems.

I would really be surprised if the `.sty` worked for you, because the bug it had (unlike the other two) should produce an error irrespective of the version of LaTeX.

> Same with the PDF generation.

You might be having an older TeX distribution then. Because I update TeX Live daily and the `ltxdoc` class strictly needs an old version of `hyperref`.

> But I completely trust that the things you've changed in that regard are better and will work more reliably, as you seem to have more experience writing LaTeX packages than I do.

Many of them are there because of generous contributions by expert LaTeX enthusiasts. It's not just me 😄, but as of now you can trust the test results (and not me 😛).

> I will review and test the code to ensure that everything works on my end and most likely approve this and make the appropriate changes to the Python script.

That sounds really great.

Also as we are at it, I wanted to add some points. Maybe you would know if Python can do it. Of course we can do these things after merging and releasing v2.0 also, because at the moment users should at least get a successful compilation.

1. Can we have an optional argument to macros which will print the language-name in it's native script? e.g., (मराठी for Marathi, 日本語 for Japanese and so on) Obviously we won't be able to do all the names alone, but if we develop the functionality; volunteers can put up PRs or issues for the inclusion of their languages. Not having any script will not produce any issue as any ways it is going to be optional.
2. As of now we produce `I have recently taken up Baure (Arawakan).` with `I have recently taken up \liso{ptk}.`, but our documentation says, 

    > One may also use the `\liso` macro to print out both the name and the ISO 639-3 code of the language specified in the macro in parenthesis, again according to its ISO code (`\liso{⟨ISO code⟩}`).

I am not a typologist, so I haven't actually worked on languages using these databases, but with what I see here, shouldn't the output be `I have recently taken up Baure (ISO 639-3 ptk)` itself? Our macro takes the ISO code as its argument, right? but what we are printing is something else only. I didn't understand this even at the time of rebuilding the package, but I decided not to change the UI at all and only rebuild the internal functions. I suggest you to clarify what exactly you are aiming to do with this macro.

> Thank you again for all the work!

That's my pleasure! Very glad to see a fellow-linguist working for the betterment of LaTeX.

**Comment by niruvt** [comment]
Now I understood what was the problem with your package!! You wanted to unlist `\csname`, `\endcsname`, and `\unskip` from the index and hence you added them in `\DoNotIndex`, but you should have added commas separating all of these which you forgot. While [beautifying the documentation](https://github.com/cicervlvs/langnames/commit/cc46f060301daa733f786938e0c51fd769ecc9c8) I came to know about this.

**Comment by cicervlvs** [comment]
> Can we have an optional argument to macros which will print the language-name in it's native script?

I will look into this, as I would also like the database to be expanded with other langugages (right now it's only in English because that's the language that the databases use. Feel free to post an issue about it.

> As of now we produce I have recently taken up Baure (Arawakan). with I have recently taken up \liso{ptk}., but our documentation says...

I also just saw this, for some reason the `\liso` package was printing the family name instead. I just reran the .dtx file and it gave me an error: `! Undefined control sequence. l.114 %   \changetonone`. It is not compiling at the moment, so I assume that there is some issue with the declaration of that command. Interestingly enough, my v1.0 that did not compile for you works just fine on my computer. Could it be a difference in versions of LaTeX? I'm currently using TexLive on Arch Linux. Please take a look at it if you have the time!

After that's fixed and everything runs normally, I'll finally merge it. Afterwards I would like to make some style changes in the text of the documentation just to make it more consistent with the rest, if you don't mind.

**Comment by cicervlvs** [comment]
Nevermind, that was just a problem with how I had my packages organized. It works now! I'll take a look into the `liso` issue now

**Comment by niruvt** [comment]
> I will look into this, as I would also like the database to be expanded with other langugages (right now it's only in English because that's the language that the databases use. Feel free to post an issue about it.

Sure, I will do it after releasing this.

> ! Undefined control sequence. l.114 % \changetonone

You would need to have the latest .sty first before compiling the documentation. If you had not compiled the .ins file you would have got this error.

> Interestingly enough, my v1.0 that did not compile for you works just fine on my computer. Could it be a difference in versions of LaTeX? I'm currently using TexLive on Arch Linux.

I am pretty sure that this must be an issue because of an older TeX distribution. Mine is TeX Live 2022 with all packages updated. You should check yours.

> After that's fixed and everything runs normally, I'll finally merge it. Afterwards I would like to make some style changes in the text of the documentation just to make it more consistent with the rest, if you don't mind.

I don't mind at all, after all _you_ are the author and its your package 😄. I have stylized it with the standard `l3doc` techniques. As far as I can see it is consistent, but if you think something needs to be changed, feel free to do so. If you want any help regarding stylizing I will be eager to help. Kindly pull all the changes before reviewing.

**Comment by niruvt** [comment]
Sorry for the pull and push conflict, using GitHub after a long time, I messed something up.

**Comment by niruvt** [comment]
> I also just saw this, for some reason the \liso package was printing the family name instead.

Sorry; had missed this.

If you confirm this to be a bug, I will fix it. It's an easy fix. Not a complicated task.

**Comment by niruvt** [comment]
Did you forget to add a `\tableofcontents` to your document? It looks nice and helpful (not pushed, just showing it for demonstration):

tableofcontents

**Comment by cicervlvs** [comment]
> I have stylized it with the standard l3doc techniques. As far as I can see it is consistent...

The documentation style in itself is not a problem at all, I'm more talking about the actual text. I'd like to make changes to it to make the manner of expression match.

> If you confirm this to be a bug, I will fix it. It's an easy fix. Not a complicated task.

Yes, I believe so. It should print the ISO 639-3 code instead. I've tested it on a different file with the same problem. Thanks!

> Did you forget to add a `\tableofcontents` to your document?

Possibly, feel free to add it!

**Comment by niruvt** [comment]
> The documentation style in itself is not a problem at all, I'm more talking about the actual text. I'd like to make changes to it to make the manner of expression match.

Oh, got it. Feel free to do it 😄.

> Yes, I believe so. It should print the ISO 639-3 code instead. I've tested it on a different file with the same problem. Thanks!

[Fixed](https://github.com/cicervlvs/langnames/pull/1/commits/88b5dc5d0980f6fc6a1b670f3037ff052be185cf).

> Possibly, feel free to add it!

[Done](https://github.com/cicervlvs/langnames/pull/1/commits/e416d538786aad37317853de34669c694f0b08f4).

**Comment by cicervlvs** [comment]
Great, just tested it, thanks!

**Comment by niruvt** [comment]
Thanks for merging! Looking ahead for a fresh version.

Another very small tip: It is advised to release new packages with the number v0.1. In community it means that the concerned package is experimental. Technically nothing wrong with any number, but conventionally v1.0 means the first _stable_ version after community feedback and testing which usually is absent in the first release. I had also committed the same mistake with my first package.

**Pull request merged**
