### PR TITLE
Add native language support

### PR DESCRIPTION
**Pull request by niruvt**
This is an experimental code which adds support for printing native language names with our package. Currently with new files and new sty the following code:

```latex
\documentclass{article}
\usepackage[glottolog,native]{langnames}
\usepackage{fontspec}
\newfontfamily\martxt[%
  Scale=0.9,%
  Script=Devanagari,%
  Renderer=Harfbuzz% Only required with LuaLaTeX
]{Shobhika}
% ctan.org/pkg/shobhika
\newfontfamily\jpntxt[Scale=0.9]{HaranoAjiMincho-Regular.otf}
% ctan.org/pkg/haranoaji

\begin{document}
The endonym of \lname{mar} is {\martxt\langnative{mar}}.\par
The endonym of \lname{jpn} is {\jpntxt\langnative{jpn}}.\par
The endonym of \lname{deu} is {\jpntxt\langnative{deu}}.
\end{document}
```

Produces:

Screenshot_2022-09-11_20-09-20

(Note: I am using fully updated TeX Live 2022.)

### CODE REVIEW

**Comment by niruvt** [comment]
I have minimally documented the two new functions. I believe you are better at documenting than me. 😛

**Comment by cicervlvs** [comment]
Looks good! Would it be possible to be able to print the native names without having to use the `\martxt` or `jpntx` macros every time? Or is that just how it works?

**Comment by niruvt** [comment]
> Looks good! Would it be possible to be able to print the native names without having to use the \martxt or jpntx macros every time? Or is that just how it works?

As they aren't in ASCII, it isn't possible to print them without a Unicode supporting font. That's what those commands do. One can of course use:

```latex
\newlangnative{glottolog}{mar}{{\martxt मराठी}}
```

but that is not how we should have it in our files is what I would suggest. One can also define:

```
\def\mycustomlangcmd{{\martxt\langnative{mar}}}
```

and use `\mycustomlangcmd` everywhere.

**Comment by cicervlvs** [comment]
Okay, if we give an example of how to actually set it up then I guess it's good enough to work!

**Comment by niruvt** [comment]
I have already added the example that I have given here in the documentation. If you have any ideas for its improvement feel free to make changes.

Also thanks for the merge.

**Pull request merged**
